version: '3'
services:
  db:
    image: mysql:5.7
    container_name: flameletlab-api-mysql
    environment:
      MYSQL_DATABASE: flameletlab
      MYSQL_ROOT_PASSWORD: root
      MYSQL_ROOT_HOST: '%'
    ports:
      - "3306:3306"
    restart: always