spring:
  jpa:
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    database: MYSQL
    hibernate:
      ddl-auto: validate
  flyway:
    enabled: true
  datasource:
    url: jdbc:mysql://flameletlab:3306/buyjunub?useTimezone=true&serverTimezone=UTC&allowPublicKeyRetrieval=true&useSSL=false
    username: root
    password: topSecretPass