spring:
  application:
    name: FlameLetLabAPI
  profiles:
    active: '@spring.profiles.active@'
  jpa:
    properties:
      javax:
        persistence:
          sharedCache:
            #required - enable selective caching mode - only entities with @Cacheable annotation will use L2 cache.
            mode: ENABLE_SELECTIVE
    hibernate:
      cache:
        #required - turn on L2 cache.
        use_second_level_cache: true
        #optional - turn on query cache.
        use_query_cache: true
        region:
          #required - classpath to cache region factory.
          factory_class: org.hibernate.cache.jcache.JCacheRegionFactory
  mail:
    host: ""
    port: 587
    username: ""
    password: ""
  thymeleaf:
    cache: true
